class AuthError extends Error {}

const corsHeaders = () => ({
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Max-Age': '86400',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'Referrer-Policy': 'strict-origin-when-cross-origin'
})

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders() }
  })

const b64UrlToBytes = (input) => {
  const pad = input.replace(/-/g, '+').replace(/_/g, '/')
  const bin = atob(pad)
  return Uint8Array.from(bin, (c) => c.charCodeAt(0))
}

const decodePayload = (payloadB64) =>
  JSON.parse(new TextDecoder().decode(b64UrlToBytes(payloadB64)))

// In-isolate JWKS cache: avoids hitting Google's JWKS endpoint on every request.
// Firebase rotates keys rarely (~24h+), so a 1h TTL is safe and keeps auth latency low.
let jwksCache = { keys: null, fetchedAt: 0 }
const JWKS_TTL_MS = 60 * 60 * 1000

async function getFirebaseJwks() {
  const now = Date.now()
  if (jwksCache.keys && now - jwksCache.fetchedAt < JWKS_TTL_MS) {
    return jwksCache.keys
  }
  const jwksUrl = 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com'
  const res = await fetch(jwksUrl)
  if (!res.ok) throw new Error('Failed to fetch Firebase JWKS keys')
  const data = await res.json()
  const keys = data.keys || []
  if (!keys.length) throw new Error('Empty JWKS response')
  jwksCache = { keys, fetchedAt: now }
  return keys
}

async function verifyFirebaseIdToken(authHeader, env) {
  if (!authHeader?.startsWith('Bearer ')) throw new AuthError('Missing bearer token')
  const token = authHeader.slice(7)
  const [headerB64, payloadB64, signatureB64] = token.split('.')
  if (!headerB64 || !payloadB64 || !signatureB64) throw new AuthError('Malformed token')

  let header, payload
  try {
    header = decodePayload(headerB64)
    payload = decodePayload(payloadB64)
  } catch {
    throw new AuthError('Malformed token encoding')
  }

  // Only accept the algorithm Firebase actually signs with (prevents alg-confusion attacks)
  if (header.alg !== 'RS256') throw new AuthError('Unsupported token algorithm')

  const projectId = env.FIREBASE_PROJECT_ID || 'localfind-2012'

  // Required claims: exp, iat, aud, iss, sub — a missing claim must fail closed
  if (!payload.exp || typeof payload.exp !== 'number' || payload.exp * 1000 < Date.now()) {
    throw new AuthError('Token expired or missing expiry')
  }
  if (!payload.iat || typeof payload.iat !== 'number') throw new AuthError('Missing issued-at claim')
  if (!payload.aud || payload.aud !== projectId) throw new AuthError('Invalid audience')
  if (!payload.iss || payload.iss !== `https://securetoken.google.com/${projectId}`) {
    throw new AuthError('Invalid issuer')
  }
  if (!payload.sub || typeof payload.sub !== 'string') throw new AuthError('Missing subject claim')

  const keys = await getFirebaseJwks()
  const jwk = keys.find((k) => k.kid === header.kid)
  if (!jwk) throw new AuthError('Unknown signing key')

  const cryptoKey = await crypto.subtle.importKey(
    'jwk',
    {
      kty: jwk.kty,
      n: jwk.n,
      e: jwk.e,
      alg: 'RS256',
      ext: true
    },
    { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' },
    false,
    ['verify']
  )

  const valid = await crypto.subtle.verify(
    'RSASSA-PKCS1-v1_5',
    cryptoKey,
    b64UrlToBytes(signatureB64),
    new TextEncoder().encode(`${headerB64}.${payloadB64}`)
  )

  if (!valid) throw new AuthError('Invalid token signature')
  return payload
}

// ---------- Input sanitization helpers ----------

const TIME_REGEX = /^([01]\d|2[0-3]):[0-5]\d$/

const cleanText = (value, maxLen) => {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return trimmed ? trimmed.slice(0, maxLen) : null
}

// Allow only http(s) links (blocks javascript:/data:/vbscript: injection stored in DB)
function sanitizeHttpUrl(value, maxLen = 2048) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim().slice(0, maxLen)
  if (!trimmed) return null
  try {
    const url = new URL(trimmed)
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.href : null
  } catch {
    return null
  }
}

// Product photos may be remote links OR inline compressed data URLs generated by the app.
// Accept http(s) and data:image/* (base64) only, with a size ceiling to prevent DB bloat.
const MAX_IMAGE_DATA_URL_CHARS = 500_000 // ~365 KB binary

function sanitizeImageUrl(value) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim().slice(0, MAX_IMAGE_DATA_URL_CHARS)
  if (!trimmed) return null
  if (/^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(trimmed)) {
    return trimmed
  }
  return sanitizeHttpUrl(trimmed)
}

function sanitizeTime(value, fallback) {
  if (typeof value === 'string' && TIME_REGEX.test(value)) return value
  return fallback
}

function sanitizeDiscount(value) {
  const num = Number(value)
  if (!Number.isFinite(num)) return 0
  return Math.min(90, Math.max(0, Math.round(num)))
}

function sanitizeFlashEndsAt(value) {
  if (!value || typeof value !== 'string') return null
  const ms = Date.parse(value)
  if (!Number.isFinite(ms)) return null
  return new Date(ms).toISOString()
}

// ---------- Request handlers ----------

async function handleCreateShop(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const shop_name = cleanText(body.shop_name, 80)
  const whatsapp_number = typeof body.whatsapp_number === 'string' ? body.whatsapp_number.replace(/[^0-9]/g, '') : ''
  const lat = Number(body.lat)
  const lng = Number(body.lng)

  if (!shop_name || !whatsapp_number) return json({ error: 'shop_name and whatsapp_number are required' }, 400)
  if (whatsapp_number.length !== 10) return json({ error: 'whatsapp_number must be exactly 10 digits' }, 400)
  if (!Number.isFinite(lat) || lat < -90 || lat > 90) {
    return json({ error: 'lat must be a number between -90 and 90' }, 400)
  }
  if (!Number.isFinite(lng) || lng < -180 || lng > 180) {
    return json({ error: 'lng must be a number between -180 and 180' }, 400)
  }

  // Atomic upsert on the unique(owner_id) index: removes the racy SELECT-then-INSERT
  // pattern (concurrent first-time saves used to collide with a UNIQUE constraint 500).
  const id = crypto.randomUUID()
  const res = await env.DB.prepare(
    `INSERT INTO shops (id, owner_id, shop_name, owner_name, description, opening_time, closing_time, whatsapp_number, lat, lng, address_text)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(owner_id) DO UPDATE SET
       shop_name   = excluded.shop_name,
       owner_name  = excluded.owner_name,
       description = excluded.description,
       opening_time = excluded.opening_time,
       closing_time = excluded.closing_time,
       whatsapp_number = excluded.whatsapp_number,
       lat = excluded.lat,
       lng = excluded.lng,
       address_text = excluded.address_text`
  ).bind(
    id,
    user.sub,
    shop_name,
    cleanText(body.owner_name, 80),
    cleanText(body.description, 500),
    sanitizeTime(body.opening_time, '09:00'),
    sanitizeTime(body.closing_time, '21:00'),
    whatsapp_number,
    lat,
    lng,
    cleanText(body.address_text, 300)
  ).run()

  if (!res.success) return json({ error: 'Failed to save shop' }, 500)

  // On conflict SQLite keeps the ORIGINAL row id, so read back the persisted row to
  // report the accurate id and whether this request created or updated the shop.
  const row = await env.DB.prepare('SELECT id FROM shops WHERE owner_id = ?').bind(user.sub).first()
  const updated = Boolean(row && row.id !== id)
  return json(row ? { id: row.id, ...(updated ? { updated: true } : { created: true }) } : { error: 'Failed to save shop' }, row ? 200 : 500)
}

async function handleCreateProduct(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const shop_id = cleanText(body.shop_id, 64)
  const name = cleanText(body.name, 120)
  const category = cleanText(body.category, 40)
  const price = Number(body.price)

  if (!shop_id || !name || !category) return json({ error: 'shop_id, name and category are required' }, 400)
  if (!Number.isFinite(price) || price < 0 || price > 10_000_000) {
    return json({ error: 'price must be a valid positive number' }, 400)
  }

  const shop = await env.DB.prepare('SELECT id, owner_id FROM shops WHERE id = ?').bind(shop_id).first()
  if (!shop) return json({ error: 'Shop not found' }, 404)
  if (shop.owner_id !== user.sub) return json({ error: 'Forbidden: shop belongs to another user' }, 403)

  const isFlashDeal = body.is_flash_deal ? 1 : 0
  const id = crypto.randomUUID()
  const now = new Date().toISOString()
  const res = await env.DB.prepare(
    `INSERT INTO products (id, shop_id, name, price, category, image_url, is_affiliate_fallback, affiliate_link, is_flash_deal, flash_deal_discount, flash_deal_ends_at, version, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)`
  ).bind(
    id,
    shop_id,
    name,
    price,
    category,
    sanitizeImageUrl(body.image_url),
    body.is_affiliate_fallback ? 1 : 0,
    sanitizeHttpUrl(body.affiliate_link),
    isFlashDeal,
    isFlashDeal ? sanitizeDiscount(body.flash_deal_discount) : 0,
    isFlashDeal ? sanitizeFlashEndsAt(body.flash_deal_ends_at) : null,
    now
  ).run()

  if (!res.success) return json({ error: 'Insert failed' }, 500)
  return json({ id }, 201)
}

async function handleUpdateProduct(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const id = cleanText(body.id, 64)
  const name = cleanText(body.name, 120)
  const category = cleanText(body.category, 40)
  const price = Number(body.price)

  if (!id || !name || !category) return json({ error: 'id, name and category are required' }, 400)
  if (!Number.isFinite(price) || price < 0 || price > 10_000_000) {
    return json({ error: 'price must be a valid positive number' }, 400)
  }

  const prod = await env.DB.prepare(
    `SELECT p.id, s.owner_id FROM products p JOIN shops s ON s.id = p.shop_id WHERE p.id = ?`
  ).bind(id).first()

  if (!prod) return json({ error: 'Product not found' }, 404)
  if (prod.owner_id !== user.sub) return json({ error: 'Forbidden: product belongs to another shopkeeper' }, 403)

  const isFlashDeal = body.is_flash_deal ? 1 : 0
  const res = await env.DB.prepare(
    `UPDATE products
     SET name = ?, price = ?, category = ?, image_url = ?, is_affiliate_fallback = ?, affiliate_link = ?,
         is_flash_deal = ?, flash_deal_discount = ?, flash_deal_ends_at = ?,
         version = COALESCE(version, 1) + 1,
         updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
     WHERE id = ?`
  ).bind(
    name,
    price,
    category,
    sanitizeImageUrl(body.image_url),
    body.is_affiliate_fallback ? 1 : 0,
    sanitizeHttpUrl(body.affiliate_link),
    isFlashDeal,
    isFlashDeal ? sanitizeDiscount(body.flash_deal_discount) : 0,
    isFlashDeal ? sanitizeFlashEndsAt(body.flash_deal_ends_at) : null,
    id
  ).run()

  if (!res.success) return json({ error: 'Update failed' }, 500)
  return json({ success: true })
}

async function handleDeleteProduct(request, env, user, url) {
  const id = url.searchParams.get('id')
  if (!id || id.length > 64) return json({ error: 'Product id parameter is required' }, 400)

  const prod = await env.DB.prepare(
    `SELECT p.id, s.owner_id FROM products p JOIN shops s ON s.id = p.shop_id WHERE p.id = ?`
  ).bind(id).first()

  if (!prod) return json({ error: 'Product not found' }, 404)
  if (prod.owner_id !== user.sub) return json({ error: 'Forbidden: product belongs to another shopkeeper' }, 403)

  const res = await env.DB.prepare('DELETE FROM products WHERE id = ?').bind(id).run()
  if (!res.success) return json({ error: 'Delete failed' }, 500)
  return json({ success: true })
}

async function handleListShops(env) {
  const { results } = await env.DB.prepare('SELECT * FROM shops ORDER BY created_at DESC').all()
  return json({ shops: results })
}

async function handleListProducts(env) {
  const { results } = await env.DB.prepare(
    `SELECT p.id, p.shop_id, p.name, p.price, p.category, p.image_url,
            p.is_affiliate_fallback, p.affiliate_link, p.is_flash_deal, p.flash_deal_discount, p.flash_deal_ends_at,
            p.version, p.updated_at, p.created_at,
            s.shop_name, s.owner_name, s.description, s.opening_time, s.closing_time, s.whatsapp_number, s.lat, s.lng, s.address_text,
            s.owner_id AS owner_id, s.owner_id AS shop_owner_id
     FROM products p
     JOIN shops s ON s.id = p.shop_id
     ORDER BY p.created_at DESC
     LIMIT 250`
  ).all()

  // Return response with 15-second Cloudflare CDN Edge Cache to reduce DB reads by ~85%
  return new Response(JSON.stringify({ products: results, app_version: '2.3.0' }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=15, s-maxage=30, stale-while-revalidate=60',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization'
    }
  })
}

// ---------- Upload handling ----------

const MAX_FILE_SIZE = 5 * 1024 * 1024

// Detect true file type from magic bytes instead of trusting the client-declared MIME type.
function sniffImageMime(bytes) {
  const b = bytes
  const startsWith = (...vals) => vals.every((v, i) => b[i] === v)
  const ascii = (offset, len) => String.fromCharCode(...b.slice(offset, offset + len))

  if (startsWith(0xff, 0xd8, 0xff)) return 'image/jpeg'
  if (startsWith(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a)) return 'image/png'
  if (ascii(0, 6) === 'GIF87a' || ascii(0, 6) === 'GIF89a') return 'image/gif'
  if (ascii(0, 4) === 'RIFF' && ascii(8, 4) === 'WEBP') return 'image/webp'
  if (ascii(4, 4) === 'ftyp') {
    const brand = ascii(8, 4).toLowerCase()
    if (['heic', 'heix', 'hevc', 'heim', 'heis', 'hevm', 'hevs', 'mif1', 'msf1'].includes(brand)) {
      return 'image/heic'
    }
  }
  return null
}

async function handleUploadImage(request, env, user) {
  if (!env.IMAGES_BUCKET) {
    return json({ error: 'R2 bucket binding "IMAGES_BUCKET" not configured on worker.' }, 500)
  }

  const formData = await request.formData().catch(() => null)
  if (!formData) return json({ error: 'Invalid form data' }, 400)

  const file = formData.get('file')
  if (!file || typeof file === 'string') return json({ error: 'No file uploaded' }, 400)

  // Security Check 1: Max upload size limit (5 MB), enforced even if client lies about size
  // by capping how many bytes we ever read into memory.
  const cappedFile = file.slice(0, MAX_FILE_SIZE + 1)
  const bytes = new Uint8Array(await cappedFile.arrayBuffer())
  if (bytes.byteLength > MAX_FILE_SIZE) {
    return json({ error: 'File too large. Maximum allowed size is 5MB.' }, 400)
  }

  // Security Check 2: Magic-byte content sniffing — never trust the declared MIME type.
  const mimeType = sniffImageMime(bytes.slice(0, 16))
  if (!mimeType) {
    return json({ error: 'Invalid file format. Only JPEG, PNG, WEBP, GIF, and HEIC images are allowed.' }, 400)
  }

  const EXT_MAP = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
    'image/gif': 'gif',
    'image/heic': 'heic'
  }
  const ext = EXT_MAP[mimeType]
  const key = `products/${user.sub}/${crypto.randomUUID()}.${ext}`

  await env.IMAGES_BUCKET.put(key, bytes, {
    httpMetadata: {
      contentType: mimeType
    }
  })

  const publicBase = env.R2_PUBLIC_URL || 'https://pub-r2.dev'
  const url = `${publicBase}/${key}`

  return json({ url, key }, 201)
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders() })

    const url = new URL(request.url)

    try {
      if (request.method === 'POST' && url.pathname === '/api/upload') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleUploadImage(request, env, user)
      }
      if (request.method === 'POST' && url.pathname === '/api/shops') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleCreateShop(request, env, user)
      }
      if (request.method === 'POST' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleCreateProduct(request, env, user)
      }
      if (request.method === 'PUT' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleUpdateProduct(request, env, user)
      }
      if (request.method === 'DELETE' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleDeleteProduct(request, env, user, url)
      }
      if (request.method === 'GET' && url.pathname === '/api/shops') {
        return await handleListShops(env)
      }
      if (request.method === 'GET' && url.pathname === '/api/products') {
        return await handleListProducts(env)
      }
      return json({ error: 'Not found' }, 404)
    } catch (err) {
      // Auth failures -> 401 with reason. Everything else -> generic 500 so internal
      // details (DB driver messages, stack traces) never leak to clients.
      if (err instanceof AuthError) {
        return json({ error: err.message }, 401)
      }
      console.error('Unhandled worker error:', err)
      return json({ error: 'Internal server error' }, 500)
    }
  }
}
