class AuthError extends Error {}

const corsHeaders = () => ({
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, If-None-Match',
  'Access-Control-Expose-Headers': 'ETag, Cache-Control',
  'Access-Control-Max-Age': '86400',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'Referrer-Policy': 'strict-origin-when-cross-origin'
})

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders() }
  })

const b64UrlToBytes = (input) => {
  const pad = input.replace(/-/g, '+').replace(/_/g, '/')
  const bin = atob(pad)
  return Uint8Array.from(bin, (c) => c.charCodeAt(0))
}

const decodePayload = (payloadB64) =>
  JSON.parse(new TextDecoder().decode(b64UrlToBytes(payloadB64)))

// In-isolate JWKS cache: avoids hitting Google's JWKS endpoint on every request.
// Firebase rotates keys rarely (~24h+), so a 1h TTL is safe and keeps auth latency low.
let jwksCache = { keys: null, fetchedAt: 0 }
const JWKS_TTL_MS = 60 * 60 * 1000

async function getFirebaseJwks() {
  const now = Date.now()
  if (jwksCache.keys && now - jwksCache.fetchedAt < JWKS_TTL_MS) {
    return jwksCache.keys
  }
  const jwksUrl = 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com'
  const res = await fetch(jwksUrl)
  if (!res.ok) throw new Error('Failed to fetch Firebase JWKS keys')
  const data = await res.json()
  const keys = data.keys || []
  if (!keys.length) throw new Error('Empty JWKS response')
  jwksCache = { keys, fetchedAt: now }
  return keys
}

async function verifyFirebaseIdToken(authHeader, env) {
  if (!authHeader?.startsWith('Bearer ')) throw new AuthError('Missing bearer token')
  const token = authHeader.slice(7)
  const [headerB64, payloadB64, signatureB64] = token.split('.')
  if (!headerB64 || !payloadB64 || !signatureB64) throw new AuthError('Malformed token')

  let header, payload
  try {
    header = decodePayload(headerB64)
    payload = decodePayload(payloadB64)
  } catch {
    throw new AuthError('Malformed token encoding')
  }

  // Only accept the algorithm Firebase actually signs with (prevents alg-confusion attacks)
  if (header.alg !== 'RS256') throw new AuthError('Unsupported token algorithm')

  const projectId = env.FIREBASE_PROJECT_ID || 'localfind-2012'

  // Required claims: exp, iat, aud, iss, sub — a missing claim must fail closed
  if (!payload.exp || typeof payload.exp !== 'number' || payload.exp * 1000 < Date.now()) {
    throw new AuthError('Token expired or missing expiry')
  }
  if (!payload.iat || typeof payload.iat !== 'number') throw new AuthError('Missing issued-at claim')
  if (!payload.aud || payload.aud !== projectId) throw new AuthError('Invalid audience')
  if (!payload.iss || payload.iss !== `https://securetoken.google.com/${projectId}`) {
    throw new AuthError('Invalid issuer')
  }
  if (!payload.sub || typeof payload.sub !== 'string') throw new AuthError('Missing subject claim')

  const keys = await getFirebaseJwks()
  const jwk = keys.find((k) => k.kid === header.kid)
  if (!jwk) throw new AuthError('Unknown signing key')

  const cryptoKey = await crypto.subtle.importKey(
    'jwk',
    {
      kty: jwk.kty,
      n: jwk.n,
      e: jwk.e,
      alg: 'RS256',
      ext: true
    },
    { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' },
    false,
    ['verify']
  )

  const valid = await crypto.subtle.verify(
    'RSASSA-PKCS1-v1_5',
    cryptoKey,
    b64UrlToBytes(signatureB64),
    new TextEncoder().encode(`${headerB64}.${payloadB64}`)
  )

  if (!valid) throw new AuthError('Invalid token signature')
  return payload
}

// ---------- Input sanitization helpers ----------

const TIME_REGEX = /^([01]\d|2[0-3]):[0-5]\d$/

const cleanText = (value, maxLen) => {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return trimmed ? trimmed.slice(0, maxLen) : null
}

// Allow only http(s) links (blocks javascript:/data:/vbscript: injection stored in DB)
function sanitizeHttpUrl(value, maxLen = 2048) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim().slice(0, maxLen)
  if (!trimmed) return null
  try {
    const url = new URL(trimmed)
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.href : null
  } catch {
    return null
  }
}

// Product photos may be remote links OR inline compressed data URLs generated by the app.
// Accept http(s) and data:image/* (base64) only, with a size ceiling to prevent DB bloat.
const MAX_IMAGE_DATA_URL_CHARS = 500_000 // ~365 KB binary

function sanitizeImageUrl(value) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim().slice(0, MAX_IMAGE_DATA_URL_CHARS)
  if (!trimmed) return null
  if (/^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(trimmed)) {
    return trimmed
  }
  return sanitizeHttpUrl(trimmed)
}

function sanitizeTime(value, fallback) {
  if (typeof value === 'string' && TIME_REGEX.test(value)) return value
  return fallback
}

function sanitizeDiscount(value) {
  const num = Number(value)
  if (!Number.isFinite(num)) return 0
  return Math.min(90, Math.max(0, Math.round(num)))
}

function sanitizeFlashEndsAt(value) {
  if (!value || typeof value !== 'string') return null
  const ms = Date.parse(value)
  if (!Number.isFinite(ms)) return null
  return new Date(ms).toISOString()
}

function sanitizeRating(value) {
  const num = Number(value)
  if (!Number.isFinite(num)) return null
  const rounded = Math.round(num)
  if (rounded < 1 || rounded > 5) return null
  return rounded
}

// ---------- Request handlers ----------

async function handleCreateShop(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const shop_name = cleanText(body.shop_name, 80)
  const whatsapp_number = typeof body.whatsapp_number === 'string' ? body.whatsapp_number.replace(/[^0-9]/g, '') : ''
  const lat = Number(body.lat)
  const lng = Number(body.lng)

  if (!shop_name || !whatsapp_number) return json({ error: 'shop_name and whatsapp_number are required' }, 400)
  if (whatsapp_number.length !== 10) return json({ error: 'whatsapp_number must be exactly 10 digits' }, 400)
  if (!Number.isFinite(lat) || lat < -90 || lat > 90) {
    return json({ error: 'lat must be a number between -90 and 90' }, 400)
  }
  if (!Number.isFinite(lng) || lng < -180 || lng > 180) {
    return json({ error: 'lng must be a number between -180 and 180' }, 400)
  }

  // Atomic upsert with RETURNING id: eliminates redundant follow-up SELECT round-trip
  const id = crypto.randomUUID()
  const row = await env.DB.prepare(
    `INSERT INTO shops (id, owner_id, shop_name, owner_name, description, opening_time, closing_time, whatsapp_number, lat, lng, address_text)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(owner_id) DO UPDATE SET
       shop_name   = excluded.shop_name,
       owner_name  = excluded.owner_name,
       description = excluded.description,
       opening_time = excluded.opening_time,
       closing_time = excluded.closing_time,
       whatsapp_number = excluded.whatsapp_number,
       lat = excluded.lat,
       lng = excluded.lng,
       address_text = excluded.address_text
     RETURNING id`
  ).bind(
    id,
    user.sub,
    shop_name,
    cleanText(body.owner_name, 80),
    cleanText(body.description, 500),
    sanitizeTime(body.opening_time, '09:00'),
    sanitizeTime(body.closing_time, '21:00'),
    whatsapp_number,
    lat,
    lng,
    cleanText(body.address_text, 300)
  ).first()

  if (!row?.id) return json({ error: 'Failed to save shop' }, 500)
  const updated = row.id !== id
  return json({ id: row.id, ...(updated ? { updated: true } : { created: true }) })
}

async function handleGetMyShop(env, user) {
  const shop = await env.DB.prepare('SELECT * FROM shops WHERE owner_id = ?').bind(user.sub).first()
  return json({ shop: shop || null })
}

async function handleCreateProduct(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const shop_id = cleanText(body.shop_id, 64)
  const name = cleanText(body.name, 120)
  const category = cleanText(body.category, 40)
  const price = Number(body.price)

  if (!shop_id || !name || !category) return json({ error: 'shop_id, name and category are required' }, 400)
  if (!Number.isFinite(price) || price < 0 || price > 10_000_000) {
    return json({ error: 'price must be a valid positive number' }, 400)
  }

  // Fast ownership check via unique index
  const shop = await env.DB.prepare('SELECT id FROM shops WHERE id = ? AND owner_id = ?').bind(shop_id, user.sub).first()
  if (!shop) return json({ error: 'Forbidden: shop not found or belongs to another user' }, 403)

  const isFlashDeal = body.is_flash_deal ? 1 : 0
  const id = crypto.randomUUID()
  const now = new Date().toISOString()
  const res = await env.DB.prepare(
    `INSERT INTO products (id, shop_id, name, price, category, image_url, is_affiliate_fallback, affiliate_link, is_flash_deal, flash_deal_discount, flash_deal_ends_at, version, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
     RETURNING id`
  ).bind(
    id,
    shop_id,
    name,
    price,
    category,
    sanitizeImageUrl(body.image_url),
    body.is_affiliate_fallback ? 1 : 0,
    sanitizeHttpUrl(body.affiliate_link),
    isFlashDeal,
    isFlashDeal ? sanitizeDiscount(body.flash_deal_discount) : 0,
    isFlashDeal ? sanitizeFlashEndsAt(body.flash_deal_ends_at) : null,
    now
  ).first()

  if (!res?.id) return json({ error: 'Insert failed' }, 500)
  return json({ id: res.id }, 201)
}

async function handleUpdateProduct(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const id = cleanText(body.id, 64)
  const name = cleanText(body.name, 120)
  const category = cleanText(body.category, 40)
  const price = Number(body.price)

  if (!id || !name || !category) return json({ error: 'id, name and category are required' }, 400)
  if (!Number.isFinite(price) || price < 0 || price > 10_000_000) {
    return json({ error: 'price must be a valid positive number' }, 400)
  }

  const isFlashDeal = body.is_flash_deal ? 1 : 0

  // Atomic single-trip update with subquery ownership authorization
  const updatedRow = await env.DB.prepare(
    `UPDATE products
     SET name = ?, price = ?, category = ?, image_url = ?, is_affiliate_fallback = ?, affiliate_link = ?,
         is_flash_deal = ?, flash_deal_discount = ?, flash_deal_ends_at = ?,
         version = COALESCE(version, 1) + 1,
         updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
     WHERE id = ? AND shop_id IN (SELECT id FROM shops WHERE owner_id = ?)
     RETURNING id`
  ).bind(
    name,
    price,
    category,
    sanitizeImageUrl(body.image_url),
    body.is_affiliate_fallback ? 1 : 0,
    sanitizeHttpUrl(body.affiliate_link),
    isFlashDeal,
    isFlashDeal ? sanitizeDiscount(body.flash_deal_discount) : 0,
    isFlashDeal ? sanitizeFlashEndsAt(body.flash_deal_ends_at) : null,
    id,
    user.sub
  ).first()

  if (!updatedRow) {
    const exists = await env.DB.prepare('SELECT id FROM products WHERE id = ?').bind(id).first()
    if (!exists) return json({ error: 'Product not found' }, 404)
    return json({ error: 'Forbidden: product belongs to another shopkeeper' }, 403)
  }

  return json({ success: true })
}

async function handleDeleteProduct(request, env, user, url) {
  const id = url.searchParams.get('id')
  if (!id || id.length > 64) return json({ error: 'Product id parameter is required' }, 400)

  // Atomic single-trip delete with subquery ownership authorization
  const deletedRow = await env.DB.prepare(
    `DELETE FROM products
     WHERE id = ? AND shop_id IN (SELECT id FROM shops WHERE owner_id = ?)
     RETURNING id`
  ).bind(id, user.sub).first()

  if (!deletedRow) {
    const exists = await env.DB.prepare('SELECT id FROM products WHERE id = ?').bind(id).first()
    if (!exists) return json({ error: 'Product not found' }, 404)
    return json({ error: 'Forbidden: product belongs to another shopkeeper' }, 403)
  }

  return json({ success: true })
}

async function handleSaveReview(request, env, user) {
  const body = await request.json().catch(() => null)
  if (!body) return json({ error: 'Invalid JSON body' }, 400)

  const shop_id = cleanText(body.shop_id, 64)
  const rating = sanitizeRating(body.rating)
  const comment = cleanText(body.comment, 500)
  const user_name = cleanText(body.user_name || user.name || 'Neighborhood Buyer', 80)

  if (!shop_id) return json({ error: 'shop_id is required' }, 400)
  if (!rating) return json({ error: 'rating must be an integer between 1 and 5' }, 400)

  // Verify shop exists
  const shop = await env.DB.prepare('SELECT id, owner_id FROM shops WHERE id = ?').bind(shop_id).first()
  if (!shop) return json({ error: 'Shop not found' }, 404)

  // Anti-fraud: Shop owners cannot review their own shop
  if (shop.owner_id === user.sub) {
    return json({ error: 'Shop owners cannot review their own shop' }, 403)
  }

  const id = crypto.randomUUID()
  const row = await env.DB.prepare(
    `INSERT INTO reviews (id, shop_id, user_id, user_name, rating, comment, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
     ON CONFLICT(user_id, shop_id) DO UPDATE SET
       user_name = excluded.user_name,
       rating = excluded.rating,
       comment = excluded.comment,
       updated_at = datetime('now')
     RETURNING id, rating, comment, updated_at`
  ).bind(id, shop_id, user.sub, user_name, rating, comment || null).first()

  return json({ success: true, review: row })
}

async function handleGetShopReviews(env, url) {
  const shopId = url.searchParams.get('shop_id')
  if (!shopId) return json({ error: 'shop_id is required' }, 400)

  const cleanShopId = cleanText(shopId, 64)

  const { results: reviews } = await env.DB.prepare(
    `SELECT id, shop_id, user_id, user_name, rating, comment, created_at, updated_at
     FROM reviews
     WHERE shop_id = ?
     ORDER BY updated_at DESC
     LIMIT 50`
  ).bind(cleanShopId).all()

  const stats = await env.DB.prepare(
    `SELECT COUNT(*) AS total_reviews,
            ROUND(AVG(rating), 1) AS avg_rating,
            SUM(CASE WHEN rating = 5 THEN 1 ELSE 0 END) AS stars_5,
            SUM(CASE WHEN rating = 4 THEN 1 ELSE 0 END) AS stars_4,
            SUM(CASE WHEN rating = 3 THEN 1 ELSE 0 END) AS stars_3,
            SUM(CASE WHEN rating = 2 THEN 1 ELSE 0 END) AS stars_2,
            SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END) AS stars_1
     FROM reviews
     WHERE shop_id = ?`
  ).bind(cleanShopId).first()

  return json({
    reviews: reviews || [],
    stats: {
      total_reviews: stats?.total_reviews || 0,
      avg_rating: stats?.avg_rating || null,
      breakdown: {
        5: stats?.stars_5 || 0,
        4: stats?.stars_4 || 0,
        3: stats?.stars_3 || 0,
        2: stats?.stars_2 || 0,
        1: stats?.stars_1 || 0
      }
    }
  })
}

async function handleDeleteReview(request, env, user, url) {
  const shopId = url.searchParams.get('shop_id')
  if (!shopId) return json({ error: 'shop_id is required' }, 400)

  const cleanShopId = cleanText(shopId, 64)
  await env.DB.prepare('DELETE FROM reviews WHERE shop_id = ? AND user_id = ?').bind(cleanShopId, user.sub).run()
  return json({ success: true })
}

async function handleListShops(env) {
  const { results } = await env.DB.prepare('SELECT * FROM shops ORDER BY created_at DESC').all()
  return json({ shops: results })
}

async function handleListProducts(env, url, request, ctx) {
  const shopId = url ? url.searchParams.get('shop_id') : null
  const category = url ? url.searchParams.get('category') : null
  const flashOnly = url ? (url.searchParams.get('flash_deals_only') === '1' || url.searchParams.get('flash_deals_only') === 'true') : false
  const since = url ? url.searchParams.get('since') : null
  const limitParam = url ? Number(url.searchParams.get('limit')) : NaN
  const limit = Number.isFinite(limitParam) && limitParam > 0 ? Math.min(500, limitParam) : 250

  const conditions = []
  const bindings = []

  if (shopId) {
    conditions.push('p.shop_id = ?')
    bindings.push(cleanText(shopId, 64))
  }
  if (category && category !== 'All') {
    conditions.push('p.category = ?')
    bindings.push(cleanText(category, 40))
  }
  if (flashOnly) {
    conditions.push("p.is_flash_deal = 1 AND (p.flash_deal_ends_at IS NULL OR p.flash_deal_ends_at > datetime('now'))")
  }
  if (since) {
    const sanitizedSince = sanitizeFlashEndsAt(since)
    if (sanitizedSince) {
      conditions.push('(p.updated_at > ? OR p.created_at > ?)')
      bindings.push(sanitizedSince, sanitizedSince)
    }
  }

  const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : ''
  const query = `
    SELECT p.id, p.shop_id, p.name, p.price, p.category, p.image_url,
           p.is_affiliate_fallback, p.affiliate_link, p.is_flash_deal, p.flash_deal_discount, p.flash_deal_ends_at,
           p.version, p.updated_at, p.created_at,
           s.shop_name, s.owner_name, s.description, s.opening_time, s.closing_time, s.whatsapp_number, s.lat, s.lng, s.address_text,
           s.owner_id AS owner_id,
           (SELECT ROUND(AVG(r.rating), 1) FROM reviews r WHERE r.shop_id = p.shop_id) AS avg_rating,
           (SELECT COUNT(r.id) FROM reviews r WHERE r.shop_id = p.shop_id) AS review_count
    FROM products p
    JOIN shops s ON s.id = p.shop_id
    ${whereClause}
    ORDER BY p.created_at DESC
    LIMIT ?`
  bindings.push(limit)

  let results
  try {
    const stmt = env.DB.prepare(query)
    const res = await stmt.bind(...bindings).all()
    results = res.results || []
  } catch (err) {
    // Fallback if reviews table not yet migrated (first deploy) - don't break product feed
    if (String(err.message || '').includes('no such table: reviews')) {
      const fallbackQuery = `
        SELECT p.id, p.shop_id, p.name, p.price, p.category, p.image_url,
               p.is_affiliate_fallback, p.affiliate_link, p.is_flash_deal, p.flash_deal_discount, p.flash_deal_ends_at,
               p.version, p.updated_at, p.created_at,
               s.shop_name, s.owner_name, s.description, s.opening_time, s.closing_time, s.whatsapp_number, s.lat, s.lng, s.address_text,
               s.owner_id AS owner_id,
               NULL AS avg_rating, 0 AS review_count
        FROM products p
        JOIN shops s ON s.id = p.shop_id
        ${whereClause}
        ORDER BY p.created_at DESC
        LIMIT ?`
      const stmt2 = env.DB.prepare(fallbackQuery)
      const res2 = await stmt2.bind(...bindings).all()
      results = res2.results || []
    } else {
      throw err
    }
  }

  // Determine if this is a global query eligible for Cloudflare Edge RAM & CDN caching
  const isGlobalPublicQuery = !shopId && !since && (!category || category === 'All') && !flashOnly
  const cacheControl = isGlobalPublicQuery
    ? 'public, max-age=45, s-maxage=90, stale-while-revalidate=180'
    : 'no-cache, no-store, must-revalidate'

  // Generate lightweight deterministic ETag fingerprint from item count + latest updated/created timestamp
  const latestRecord = results.length > 0 ? (results[0].updated_at || results[0].created_at || '0') : 'empty'
  const etag = `W/"${results.length}-${latestRecord}"`

  // Zero-Bandwidth ETag check: Return 304 Not Modified if client catalog is already up to date
  const clientEtag = request?.headers?.get('If-None-Match')
  if (clientEtag && clientEtag === etag) {
    return new Response(null, {
      status: 304,
      headers: {
        'ETag': etag,
        'Cache-Control': cacheControl,
        ...corsHeaders()
      }
    })
  }

  const response = new Response(JSON.stringify({ products: results, app_version: '2.3.0' }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': cacheControl,
      'ETag': etag,
      ...corsHeaders()
    }
  })

  // Store in Cloudflare native edge RAM cache for subsequent hits
  if (isGlobalPublicQuery && typeof caches !== 'undefined' && caches.default && ctx?.waitUntil && request) {
    try {
      const cacheKey = new Request(url.origin + url.pathname, request)
      ctx.waitUntil(caches.default.put(cacheKey, response.clone()))
    } catch (e) {
      console.warn('Edge cache write error:', e)
    }
  }

  return response
}

// ---------- Upload handling ----------

const MAX_FILE_SIZE = 5 * 1024 * 1024

// Detect true file type from magic bytes instead of trusting the client-declared MIME type.
function sniffImageMime(bytes) {
  const b = bytes
  const startsWith = (...vals) => vals.every((v, i) => b[i] === v)
  const ascii = (offset, len) => String.fromCharCode(...b.slice(offset, offset + len))

  if (startsWith(0xff, 0xd8, 0xff)) return 'image/jpeg'
  if (startsWith(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a)) return 'image/png'
  if (ascii(0, 6) === 'GIF87a' || ascii(0, 6) === 'GIF89a') return 'image/gif'
  if (ascii(0, 4) === 'RIFF' && ascii(8, 4) === 'WEBP') return 'image/webp'
  if (ascii(4, 4) === 'ftyp') {
    const brand = ascii(8, 4).toLowerCase()
    if (['heic', 'heix', 'hevc', 'heim', 'heis', 'hevm', 'hevs', 'mif1', 'msf1'].includes(brand)) {
      return 'image/heic'
    }
  }
  return null
}

async function handleUploadImage(request, env, user) {
  if (!env.IMAGES_BUCKET) {
    return json({ error: 'R2 bucket binding "IMAGES_BUCKET" not configured on worker.' }, 500)
  }

  const formData = await request.formData().catch(() => null)
  if (!formData) return json({ error: 'Invalid form data' }, 400)

  const file = formData.get('file')
  if (!file || typeof file === 'string') return json({ error: 'No file uploaded' }, 400)

  // Security Check 1: Max upload size limit (5 MB), enforced even if client lies about size
  // by capping how many bytes we ever read into memory.
  const cappedFile = file.slice(0, MAX_FILE_SIZE + 1)
  const bytes = new Uint8Array(await cappedFile.arrayBuffer())
  if (bytes.byteLength > MAX_FILE_SIZE) {
    return json({ error: 'File too large. Maximum allowed size is 5MB.' }, 400)
  }

  // Security Check 2: Magic-byte content sniffing — never trust the declared MIME type.
  const mimeType = sniffImageMime(bytes.slice(0, 16))
  if (!mimeType) {
    return json({ error: 'Invalid file format. Only JPEG, PNG, WEBP, GIF, and HEIC images are allowed.' }, 400)
  }

  const EXT_MAP = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
    'image/gif': 'gif',
    'image/heic': 'heic'
  }
  const ext = EXT_MAP[mimeType]
  const key = `products/${user.sub}/${crypto.randomUUID()}.${ext}`

  await env.IMAGES_BUCKET.put(key, bytes, {
    httpMetadata: {
      contentType: mimeType
    }
  })

  const publicBase = env.R2_PUBLIC_URL || 'https://pub-r2.dev'
  const url = `${publicBase}/${key}`

  return json({ url, key }, 201)
}

export default {
  async fetch(request, env, ctx) {
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders() })

    const url = new URL(request.url)

    try {
      if (request.method === 'POST' && url.pathname === '/api/upload') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleUploadImage(request, env, user)
      }
      if (request.method === 'POST' && url.pathname === '/api/shops') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleCreateShop(request, env, user)
      }
      if (request.method === 'POST' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleCreateProduct(request, env, user)
      }
      if (request.method === 'PUT' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleUpdateProduct(request, env, user)
      }
      if (request.method === 'DELETE' && url.pathname === '/api/products') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleDeleteProduct(request, env, user, url)
      }
      if (request.method === 'GET' && url.pathname === '/api/my-shop') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleGetMyShop(env, user)
      }
      if (request.method === 'POST' && url.pathname === '/api/reviews') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleSaveReview(request, env, user)
      }
      if (request.method === 'GET' && url.pathname === '/api/reviews') {
        return await handleGetShopReviews(env, url)
      }
      if (request.method === 'DELETE' && url.pathname === '/api/reviews') {
        const user = await verifyFirebaseIdToken(request.headers.get('Authorization'), env)
        return await handleDeleteReview(request, env, user, url)
      }
      if (request.method === 'GET' && url.pathname === '/api/shops') {
        return await handleListShops(env)
      }
      if (request.method === 'GET' && url.pathname === '/api/products') {
        const shopId = url.searchParams.get('shop_id')
        const since = url.searchParams.get('since')
        const category = url.searchParams.get('category')
        const flashOnly = url.searchParams.get('flash_deals_only') === '1' || url.searchParams.get('flash_deals_only') === 'true'
        const isGlobalPublicQuery = !shopId && !since && (!category || category === 'All') && !flashOnly

        // Check Cloudflare Edge RAM cache for lightning-fast ~8ms response
        if (isGlobalPublicQuery && typeof caches !== 'undefined' && caches.default) {
          try {
            const cacheKey = new Request(url.origin + url.pathname, request)
            const cachedRes = await caches.default.match(cacheKey)
            if (cachedRes) {
              const clientEtag = request.headers.get('If-None-Match')
              const cachedEtag = cachedRes.headers.get('ETag')

              if (clientEtag && cachedEtag && clientEtag === cachedEtag) {
                return new Response(null, {
                  status: 304,
                  headers: {
                    'ETag': cachedEtag,
                    'Cache-Control': cachedRes.headers.get('Cache-Control') || 'public, max-age=45',
                    ...corsHeaders()
                  }
                })
              }

              const fastRes = new Response(cachedRes.body, cachedRes)
              Object.entries(corsHeaders()).forEach(([k, v]) => fastRes.headers.set(k, v))
              return fastRes
            }
          } catch (cacheErr) {
            console.warn('Cache lookup error, falling through to D1:', cacheErr)
          }
        }

        return await handleListProducts(env, url, request, ctx)
      }
      return json({ error: 'Not found' }, 404)
    } catch (err) {
      // Auth failures -> 401 with reason. Everything else -> generic 500 so internal
      // details (DB driver messages, stack traces) never leak to clients.
      if (err instanceof AuthError) {
        return json({ error: err.message }, 401)
      }
      console.error('Unhandled worker error:', err)
      return json({ error: 'Internal server error' }, 500)
    }
  }
}
