/**
 * Renders only http(s) URLs. Returns null for anything else
 * (javascript:, data:, vbscript:, malformed strings), preventing stored-XSS via href/src.
 */
export function sanitizeHttpUrl(value, maxLen = 2048) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim().slice(0, maxLen)
  if (!trimmed) return null
  try {
    const url = new URL(trimmed)
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.href : null
  } catch {
    return null
  }
}

/**
 * For product images: allows http(s) plus inline base64 data:image/* URLs
 * generated by the in-app compressor. Blocks every other scheme.
 */
const SAFE_DATA_IMAGE_REGEX = /^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/

export function sanitizeImageUrl(value, maxLen = 500_000) {
  if (!value || typeof value !== 'string') return null
  const trimmed = value.trim()
  if (trimmed.length <= maxLen && SAFE_DATA_IMAGE_REGEX.test(trimmed)) {
    return trimmed
  }
  return sanitizeHttpUrl(value)
}
