name = "localfind-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "localfind-db"
database_id = "65eca607-52b0-4f67-bae9-5441305050fd"

# [[kv_namespaces]]
# binding = "JWKS_CACHE"
# id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"

[vars]
FIREBASE_CERTS_URL = "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com"
FIREBASE_AUD = "localfind-2012"
FIREBASE_PROJECT_ID = "localfind-2012"

# [[r2_buckets]]
# binding = "IMAGES_BUCKET"
# bucket_name = "localfind-images"
